spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_db
    username: jdbc_test
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update